using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("NorthScale.Store")]
[assembly: AssemblyProduct("NorthScale.Store")]

[assembly: AssemblyCompany("enyim.com")]
[assembly: AssemblyCopyright("Copyright © enyim.com, Attila Kiskó 2010")]

[assembly: AssemblyConfiguration("")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]

[assembly: ComVisible(false)]

[assembly: Guid("8460330E-5027-4e2c-AA84-FC8539780160")]

[assembly: AssemblyVersion("2.5.0.0")]
// generated by the build script
//[assembly: AssemblyFileVersion("2.4.0.0")]

#if SIGN
[assembly: AssemblyKeyName("enyim")]
#endif

#region [ License information          ]
/* ************************************************************
 * 
 *    Copyright (c) 2010 Attila Kiskó, enyim.com
 *    
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *    
 *        http://www.apache.org/licenses/LICENSE-2.0
 *    
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 *    
 * ************************************************************/
#endregion
